CREATE TABLE IF NOT EXISTS `bar`.`bar` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `code` VARCHAR(64) NOT NULL COMMENT 'Code',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Bar';
